app:
  host: 0.0.0.0
  port: 8080

workers:
  max_workers: 1


document:
  log: /dev/stdout
  verbose: true
  quiet: false
  fail_if_warnings: false
  extra_args:
    template: tests/templates/simple.tex
    pdf-engine: /Library/TeX/texbin/pdflatex
